# Generated by Django 5.2.11 on 2026-02-07 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Fiction', [('fantasy', 'Fantasy'), ('scifi', 'Science Fiction'), ('mystery', 'Mystery / Detective'), ('thriller', 'Thriller / Suspense'), ('romance', 'Romance'), ('horror', 'Horror'), ('historical', 'Historical Fiction'), ('adventure', 'Adventure'), ('ya', 'Young Adult (YA)'), ('short_story', 'Short Stories')]), ('Non-Fiction', [('biography', 'Biography / Autobiography'), ('self_help', 'Self-Help'), ('history', 'History'), ('science', 'Science & Technology'), ('philosophy', 'Philosophy'), ('psychology', 'Psychology'), ('business', 'Business & Economics'), ('travel', 'Travel'), ('health', 'Health & Fitness'), ('essays', 'Essays')]), ('Academic', [('textbook', 'Textbooks'), ('reference', 'Reference Books'), ('research', 'Research Papers'), ('journal', 'Journals'), ('exam', 'Exam Preparation')]), ('Children', [('picture', 'Picture Books'), ('early', 'Early Readers'), ('fairy', 'Fairy Tales'), ('comic', 'Comics & Graphic Novels')]), ('Style', [('novel', 'Novels'), ('novella', 'Novellas'), ('poetry', 'Poetry'), ('drama', 'Drama / Plays')])], default='novel', max_length=50)),
                ('book_format', models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('ebook', 'E-book'), ('audiobook', 'Audiobook')], default='paperback', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssuedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
