# Generated by Django 5.2.11 on 2026-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=10),
        ),
    ]
